import pandas as pd
from rdkit import Chem
import glob
import os
import multiprocessing
import time
from tqdm import tqdm

# Configuration
MOLPORT_DIR = 'temp_data/Molport_SMILES'
OUTPUT_FILE = 'purchasable_molecules_match.csv'
PRED_FILES = {
    'BAA-3170': 'temp_data/SMs_mic_predictions_BAA-3170_filtered_below_15.csv',
    'BAA-3197': 'temp_data/SMs_mic_predictions_BAA-3197_filtered_below_15.csv'
}
CHUNK_SIZE = 10000

def canonicalize_smiles(smi):
    """
    Canonicalizes a SMILES string using RDKit.
    Returns None if invalid.
    """
    if not isinstance(smi, str):
        return None
    mol = Chem.MolFromSmiles(smi)
    if mol is None:
        return None
    return Chem.MolToSmiles(mol, canonical=True, isomericSmiles=True)

def process_chunk(chunk, query_smiles_set):
    """
    Worker function to process a chunk of (SMILES, ID) tuples.
    """
    matches = []
    # chunk is list of tuples: (molport_smi, mol_id)
    
    for molport_smi, mol_id in chunk:
        # User requested to use the file's CANONICAL column as input source
        # But we MUST re-canonicalize with RDKit to ensure match with our query set
        # which was generated by RDKit. 
        # Even if the file column is named SMILES_CANONICAL, it might differ from RDKit's current version output
        # (as seen in debug_3.py). So we treat it as just a string candidate and re-canonicalize.
        
        canon_smi = canonicalize_smiles(molport_smi)
        if canon_smi and canon_smi in query_smiles_set:
            matches.append({
                'Molport_ID': mol_id,
                'Molport_SMILES': molport_smi, # This is the string from the file (read from SMILES_CANONICAL col)
                'Canonical_SMILES': canon_smi
            })
    return matches

def main():
    start_time = time.time()
    
    # 1. Load Query Molecules
    print("Loading query molecules...")
    query_map = {} 
    
    for strain, path in PRED_FILES.items():
        if not os.path.exists(path):
            print(f"Warning: File {path} not found.")
            continue
            
        df = pd.read_csv(path)
        score_col = [c for c in df.columns if 'BAA' in c or 'score' in c.lower()]
        score_col = score_col[0] if score_col else df.columns[-1]
            
        print(f"Loaded {len(df)} rows from {path}")
        
        for _, row in tqdm(df.iterrows(), total=len(df), desc=f"Canonicalizing {strain}"):
            smi = row['SMILES_Sequence']
            score = row[score_col]
            
            canon_smi = canonicalize_smiles(smi)
            if canon_smi:
                if canon_smi not in query_map:
                    query_map[canon_smi] = []
                query_map[canon_smi].append({
                    'Strain': strain,
                    'Original_Score': score,
                    'Query_SMILES': smi
                })
    
    query_smiles_set = set(query_map.keys())
    print(f"Total unique query molecules to match: {len(query_smiles_set)}")
    
    # 2. Load All Molport Data into Memory
    molport_files = glob.glob(os.path.join(MOLPORT_DIR, '*.txt'))
    print(f"Loading {len(molport_files)} Molport files into memory...")
    
    all_molport_data = [] # List of (SMILES, ID)
    
    for f in tqdm(molport_files, desc="Reading files"):
        try:
            # User requested using SMILES_CANONICAL column
            df = pd.read_csv(f, sep='\t', on_bad_lines='skip', quoting=3, usecols=['SMILES_CANONICAL', 'MOLPORTID'])
            
            # Convert to list of tuples for fast iteration
            # Dropna to be safe
            file_data = df.dropna().values.tolist()
            all_molport_data.extend(file_data)
        except Exception as e:
            print(f"Error reading {f}: {e}")
            
    total_molport = len(all_molport_data)
    print(f"Total Molport molecules loaded: {total_molport}")
    
    # 3. Parallel Processing
    # Shuffle or just chunk? Linear chunk is fine.
    # Create chunks
    chunks = [all_molport_data[i:i + CHUNK_SIZE] for i in range(0, total_molport, CHUNK_SIZE)]
    print(f"Split into {len(chunks)} chunks of size {CHUNK_SIZE}")
    
    print(f"Starting parallel processing with {multiprocessing.cpu_count()} cores...")
    
    # Prepare args
    pool_args = [(chk, query_smiles_set) for chk in chunks]
    
    all_matches = []
    with multiprocessing.Pool() as pool:
        # chunks are already batched data, so chunksize=1 for starmap is correct (1 chunk per task)
        results = list(tqdm(pool.starmap(process_chunk, pool_args), total=len(chunks), desc="Processing chunks"))
        
    for res in results:
        all_matches.extend(res)
        
    print(f"Found {len(all_matches)} raw matches.")
    
    # 4. Integrate Results
    print("Integrating results...")
    final_rows = []
    
    for match in all_matches:
        canon_smi = match['Canonical_SMILES']
        if canon_smi in query_map:
            for origin in query_map[canon_smi]:
                row = {
                    'Strain': origin['Strain'],
                    'Original_Score': origin['Original_Score'],
                    'Query_SMILES': origin['Query_SMILES'],
                    'Molport_ID': match['Molport_ID'],
                    'Molport_SMILES_Source': match['Molport_SMILES'], # Renamed
                    'Molport_Canonical_SMILES': canon_smi
                }
                final_rows.append(row)
                
    result_df = pd.DataFrame(final_rows)
    result_df.to_csv(OUTPUT_FILE, index=False)
    
    elapsed = time.time() - start_time
    print(f"Done in {elapsed:.2f} seconds.")
    print(f"Saved {len(result_df)} matches to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
